# (PART) Explainable ML  {-} 

# Explainable ML tbd {#ExplainableMl}
adfdasf

## Lime tbd

First paper on **LIME** was [@tulio2016should]


## alibi  tbd
https://github.com/SeldonIO/alibi

https://docs.seldon.io/projects/alibi/en/stable/overview/algorithms.html

## tf-explain tbd
https://github.com/sicara/tf-explain


## keras-salient-object-visualization

Keras implementation of nvidia paper 'Explaining How a Deep Neural Network Trained with End-to-End Learning Steers a Car'. The goal of the visualization is to explain what Donkey Car (https://github.com/wroscoe/donkey) learns and how it makes its decisions. The central idea in discerning the salient objects is finding parts of the image that correspond to locations where the feature maps of CNN layers have the greatest activations.

Original paper: https://arxiv.org/pdf/1704.07911.pdf 
https://arxiv.org/abs/1704.07911 

### Explaining How a Deep Neural Network Trained with End-to-End Learning Steers a Car
[@bojarski2017explaining]

- Enable further system improvement
- Create trust that the system is paying attention to the essential cues


### VisualBackProp: efficient visualization of CNNs

[@bojarski2016visualbackprop]


https://arxiv.org/abs/1611.05418 
